/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DescribeRouteImport } from './routes/describe'
import { Route as OrangeRouteImport } from './routes/orange'
import { Route as RedRouteImport } from './routes/red'
import { Route as SentRouteImport } from './routes/sent'
import { Route as YellowRouteImport } from './routes/yellow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DescribeRoute = DescribeRouteImport.update({
  id: '/describe',
  path: '/describe',
  getParentRoute: () => rootRouteImport,
} as any)
const OrangeRoute = OrangeRouteImport.update({
  id: '/orange',
  path: '/orange',
  getParentRoute: () => rootRouteImport,
} as any)
const RedRoute = RedRouteImport.update({
  id: '/red',
  path: '/red',
  getParentRoute: () => rootRouteImport,
} as any)
const SentRoute = SentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const YellowRoute = YellowRouteImport.update({
  id: '/yellow',
  path: '/yellow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/describe': typeof DescribeRoute
  '/orange': typeof OrangeRoute
  '/red': typeof RedRoute
  '/sent': typeof SentRoute
  '/yellow': typeof YellowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/describe': typeof DescribeRoute
  '/orange': typeof OrangeRoute
  '/red': typeof RedRoute
  '/sent': typeof SentRoute
  '/yellow': typeof YellowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/describe': typeof DescribeRoute
  '/orange': typeof OrangeRoute
  '/red': typeof RedRoute
  '/sent': typeof SentRoute
  '/yellow': typeof YellowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/alerts' | '/describe' | '/orange' | '/red' | '/sent' | '/yellow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/describe' | '/orange' | '/red' | '/sent' | '/yellow'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/describe'
    | '/orange'
    | '/red'
    | '/sent'
    | '/yellow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DescribeRoute: typeof DescribeRoute
  OrangeRoute: typeof OrangeRoute
  RedRoute: typeof RedRoute
  SentRoute: typeof SentRoute
  YellowRoute: typeof YellowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/describe': {
      id: '/describe'
      path: '/describe'
      fullPath: '/describe'
      preLoaderRoute: typeof DescribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orange': {
      id: '/orange'
      path: '/orange'
      fullPath: '/orange'
      preLoaderRoute: typeof OrangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red': {
      id: '/red'
      path: '/red'
      fullPath: '/red'
      preLoaderRoute: typeof RedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sent': {
      id: '/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof SentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yellow': {
      id: '/yellow'
      path: '/yellow'
      fullPath: '/yellow'
      preLoaderRoute: typeof YellowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DescribeRoute: DescribeRoute,
  OrangeRoute: OrangeRoute,
  RedRoute: RedRoute,
  SentRoute: SentRoute,
  YellowRoute: YellowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
