/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as OrangeRouteImport } from './routes/orange'
import { Route as RedRouteImport } from './routes/red'
import { Route as YellowRouteImport } from './routes/yellow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrangeRoute = OrangeRouteImport.update({
  id: '/orange',
  path: '/orange',
  getParentRoute: () => rootRouteImport,
} as any)
const RedRoute = RedRouteImport.update({
  id: '/red',
  path: '/red',
  getParentRoute: () => rootRouteImport,
} as any)
const YellowRoute = YellowRouteImport.update({
  id: '/yellow',
  path: '/yellow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/orange': typeof OrangeRoute
  '/red': typeof RedRoute
  '/yellow': typeof YellowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/orange': typeof OrangeRoute
  '/red': typeof RedRoute
  '/yellow': typeof YellowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/orange': typeof OrangeRoute
  '/red': typeof RedRoute
  '/yellow': typeof YellowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerts' | '/orange' | '/red' | '/yellow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/orange' | '/red' | '/yellow'
  id: '__root__' | '/' | '/alerts' | '/orange' | '/red' | '/yellow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  OrangeRoute: typeof OrangeRoute
  RedRoute: typeof RedRoute
  YellowRoute: typeof YellowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orange': {
      id: '/orange'
      path: '/orange'
      fullPath: '/orange'
      preLoaderRoute: typeof OrangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red': {
      id: '/red'
      path: '/red'
      fullPath: '/red'
      preLoaderRoute: typeof RedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yellow': {
      id: '/yellow'
      path: '/yellow'
      fullPath: '/yellow'
      preLoaderRoute: typeof YellowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  OrangeRoute: OrangeRoute,
  RedRoute: RedRoute,
  YellowRoute: YellowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
